/** Full help reference for the web workbench (? overlay). */
export const WEB_HELP_LINES: readonly string[] = [
  "── Playback & Pattern ─────────────────────────────────────────",
  "  /play / /stop                        start or stop playback",
  "  /bpm <n>                             set BPM (20–400)",
  "  /swing <n>                           set swing 0–100",
  "  /length [8|16|32]                    pattern step count",
  "  /prob / /vel / /gate / /pitch        track-wide step params",
  "  /cond <track> <step> <1:2|not:2|fill|clear>",
  "  /random <track|all> <vel|prob> [lo-hi]",
  "  /randbeat                            random techno beat",
  "  /mute <track> [on|off|toggle]        queue mute at next bar",
  "  /cc / /cc-step / /lfo                mix & modulation routes",
  "  /save / /load / /delete / /patterns  pattern library",
  "  /fill / /chain …                     fills & setlists",
  "  /new / /undo / /midi / /midi list",
  "",
  "── Chat & Generation ──────────────────────────────────────────",
  "  plain text in CHAT                   generate beat from prompt",
  "  /ask <question>                      Q&A (CMD bar)",
  "  /fresh / /gen / /mode / /next / /vary / /read",
  "",
  "── Keyboard shortcuts ─────────────────────────────────────────",
  "Global",
  "  ?                                    this help overlay",
  "  m / q / Shift+Q                      mute now / stage / fire at next bar",
  "  Space                                play/stop (when not typing)",
  "  Tab / Shift+Tab                      cycle panes SEQ → workbench → CHAT",
  "",
  "Pane jump",
  "  S SEQ   I MIX   T TRIG   L LFO   C CHAT",
  "  : or ⌘K                              CMD bar",
  "  /                                    focus CHAT composer",
  "  Esc                                  return to SEQ",
  "",
  "SEQ",
  "  ↑↓ track · ←→ step · Enter toggle step · m/q/Q mute selected track",
  "",
  "TRIG / MIX / LFO",
  "  ↑↓ param/field · ←→ value · [ ] track (SEQ/MIX)",
  "  Enter TRIG toggle · , . MIX nudge · ( ) LFO slot · + − LFO add/del",
  "",
  "Footer",
  "  M/Q on track rows: yellow Q = staged · red Q = armed for next bar",
  "",
  "Press ? or Esc to close",
];
